### ISSUE TITLE
immediate crash on first start after installation

### ISSUE THREAD

**Issue by theralmccoy1234** [Infinity-Evolved-Reloaded-Modpacks/Infinity-Evolved-Reloaded#240]
I installed the modpack on multimc running on a Linux Mint machine (java V11.0.11). It crashes right after startup

**General Info (please complete the following information):**
 - Modpack version: 3.7.1
 - Client or server: client
 - Packmode: none (startup right after installation)
 - Own modifications to the modpack: none

**Describe the bug**
The Mod crashes almost immediatly at startup

**To Reproduce**
E.g.:
2. Try to '...'
3. See error.

**Screenshots**
[If applicable, add screenshots to help explain your problem.]

**Crash-log**
Params:
  --username  --version MultiMC5 --gameDir /home/mario/.local/share/multimc/instances/Infinity Evolved Reloaded/minecraft --assetsDir /home/mario/.local/share/multimc/assets --assetIndex 1.12 --uuid  --accessToken  --userType  --versionType release --tweakClass net.minecraftforge.fml.common.launcher.FMLTweaker

Window size: 854 x 480

Java Arguments:
[-Xms1024m, -Xmx7168m, -Duser.language=en]

Minecraft process ID: 6822

Using onesix launcher.

Failed to start Minecraft:
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
Exiting with -1
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
	at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	... 8 more
Der Prozess wurde mit Status 255 beendet.

**Comment by fabrossmann** [comment]
Pre 1.13 Forge is only compatible with Java 8, you will have to change your JRE
