### ISSUE TITLE
What Java Version Do We Use To Run A Server For Infinity Evolved Reloaded?

### ISSUE THREAD

**Issue by Garretttru** [Infinity-Evolved-Reloaded-Modpacks/Infinity-Evolved-Reloaded#244]
Hello,
I installed Java 17 but when I click Start Server.bat it gives this in the console:
Am I using the wrong Java?

A problem occurred running the Server launcher.java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:70)
        at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:34)
Caused by: java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
        at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
        ... 6 more
Press any key to continue . . .

Thanks,

-Garrett

**Comment by Garretttru** [comment]
I tried running the server start.bat file as admin and I got this error:

Error: Unable to access jarfile forge-1.12.2-14.23.5.2860.jar

**Comment by fabrossmann** [comment]
Every 1.12 Modpack need Java 8

**Comment by Garretttru** [comment]
thx. it is working now
