### ISSUE TITLE
Server not starting

### ISSUE THREAD

**Issue by TheFrenchSeal** [Infinity-Evolved-Reloaded-Modpacks/Infinity-Evolved-Reloaded#265]
This is what happens when i try to start the server with the server .bat i have java 8 installed same with the runtime help will be apreciated this is the error

A problem occurred running the Server launcher.java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:110)
        at java.base/java.lang.reflect.Method.invoke(Method.java:577)
        at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:70)
        at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:34)
Caused by: java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
        at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
        ... 3 more

**Comment by SanderWxD** [comment]
Wrong java version. Delete your installed java and download JRE(Java Runtime Environment) 8u321.

**Comment by TheFrenchSeal** [comment]
Could you possibly send the download link because im not sure wich one i need to download

**Comment by MojangPlsFix** [comment]
> Could you possibly send the download link because im not sure wich one i need to download

https://adoptopenjdk.net/releases.html

Select OpenJDK 8 and Hotspot.
